#!/usr/bin/env python3
#
#   Author: Vincent Perricone <vhp@fastmail.fm>
#   Date: 11/22/2017
#   Title: FICT: file intergrity checking tool
#   License: Released under "Simplified BSD License" see LICENSE file
#
"""
Usage:
    fict [options]
    fict init [options]
    fict add (<path>) [options]
    fict status
    fict compute [options]
    fict list [options]
    fict check [<path>] [options]
    fict (-h | --help)

Generic options:
    --fict-db-name=FILE         DB filename.         [default: fict_db]
    --fict-dir=DIRECTORY        Path of fict Directory. [default: ~/.fict]
    --hash-tool=FILE            Hashing Tool        [default: sha512sum]
    --recompute                 Recompute Checksums (By Force)
    -y, --yes                   Agree ahead of time.
    -v, --verbose               Verbos/Debug Output.
    -h, --help                  Show Help.
"""
import sys
import os
from docopt import docopt
from lib import core

fict_dir_name_default = '.fict'

if __name__ == '__main__':
    args = docopt(__doc__)
    args['--fict-dir'] = os.path.expanduser(args['--fict-dir'])
    if args['<path>']:
        args['<path>'] = os.path.abspath(args['<path>'])
    sys.exit(core.main(args))
